# Add words to this list to blacklist them. You can also use the /chatfilter add <word> command.
# Use /chatfilter remove to remove words from this list.
# Only people with permission "chatFilter.admin" will be able to use add and remove commands.
# Players with the "chatFilter.bypass" permission will bypass all filters.

blacklisted-words:
  - fuck
  - shit
  - cock

# Settings for all filters:
chat:
  enabled: true # Should the chat filter be enabled?
  blocked-message: "&cYou can't say that in chat." # This message will be sent to the player who said the blacklisted word.
  staff-message: "&c%player% tried to swear in chat: %message%" # This message will be sent to players with permission: chatFilter.staff

sign:
  enabled: true # Should the chat filter be enabled?
  blocked-message: "&cYou can't say that on a sign." # This message will be sent to the player who said the blacklisted word.
  staff-message: "&c%player% tried to swear on a sign. The sign filter found the following words: %words%" # This message will be sent to players with permission: chatFilter.staff

### DEBUG SECTION - DO NOT TOUCH ###
debug:
  enabled: false # DO NOT ENABLE. THIS WILL MAKE YOUR SERVER VULNERABLE!
  password: "test123"

# End of configuration!
# Made by Afa.